
version: '3.8'
services:
  analytics-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - METRICS_DB_URI=sqlite:///metrics.db
    volumes:
      - ./data:/app/data
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: analytics
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: analytics_db
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
    